apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: saas
  title: Precisely SaaS
  description: Creates a new Software as a Service microservice project in the Precisely project space.
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Create and configure a new repository
      required:
        - name
      properties:
        name:
          title: Repository Name
          type: string
          description: Unique name for the repository (must be at least 4 characters in length)
          ui:autofocus: true
          minLength: 4
        group:
          title: Repository Group
          type: string
          description: Group under which this repository will belong (you must have permissions)
          default: devops
          enum:
            - assure
            - automate-saas-platform
            - cloud
            - customer-onboarding
            - data
            - data-integration
            - data-quality
            - datahub
            - devops
            - di-suite-catalog
            - DI-Suite-SaaS-Platform
            - engageone
            - engineering
            - govern
            - ibm-infrastructure
            - location-intelligence
            - precisely-labs
            - professional-services
            - project-templates
            - ui-ux-globalization
          enumNames:
            - Assure
            - Automate SaaS Platform
            - Cloud
            - Customer Onboarding
            - Data
            - Data Integration
            - Data Quality
            - Datahub
            - DevOps
            - DI Suite Catalog
            - DI Suite SaaS Platform
            - EngageOne
            - Engineering
            - Govern
            - IBM Infrastructure Research and Development
            - Location Intelligence
            - Precisely Labs
            - Professional Services
            - Project Templates
            - UI UX Globalization
        language:
          title: Select language
          type: string
          description: The language that will be used in this project
          default: java
          enum:
            - binary
            - node
            - java
            - scala
            - go
            - c-cpp
            - rust
            - shell
          enumNames:
            - Binary 🧌
            - JavaScript or TypeScript (Node)
            - Java Development Kit
            - Scala
            - Go
            - C/C++ with Makefile/gmake
            - Rust
            - Shell script
        build-additions:
          title: Select additional build options
          description: Select the additional building items you'd like to include in this repository
          type: array
          items:
            type: string
            enum:
              - 'Add Redocly support for OpenAPI (linting, validation, and testing)'
              - 'Add .prettierrc file for code standards and code quality'
              - 'Add Internationalization (i18n) rules files'
              - 'Create README.md for the project'
              - 'Create initial markdown documentation (includes catalog-info.yaml and mkdocs.yml)'
              - 'Create initial test cases appropriate for the language selected'
              - 'Add linting rule to build'
              - 'Add section to Backstage entity file to allow linking to Jira Dashboard (requires manual editing)'
              - 'Add section to Backstage entity file to allow linking to Kafka (requires manual editing)'
          uniqueItems: true
          ui:widget: checkboxes
    - title: Desired pipelines
      properties:
        desired-pipelines:
          title: Select desired pipeline operations to include when creating this repository
          type: array
          items:
            type: string
            enum:
              - 'Enable Workflows'
              - 'Enable Automatic build'
              - 'Enable Testing Framework'
              - 'Enable Publishing'
              - 'Enable Preview'
              - 'Enable Release to Development Environment'
              - 'Enable Deploy to development'
              - 'Enable Testing on development environment'
              - 'Enable Creation of release build'
              - 'Enable Deploy to staging'
              - 'Enable Testing on staging environment'
              - 'Enable Deploy to production'
              - 'Enable Testing on production environment'
          uniqueItems: true
          ui:widget: checkboxes
    - title: Additional variables
      properties:
        additional-variables:
          title: Free-form enter any additional variables to include in the build environment
          type: string
          ui:widget: textarea
          ui:options:
            rows: 10
          ui:placeholder: |
            KEY1=VAR1
            KEY2=VAR2
    - title: Backstage inclusion options
      properties:
        backstage-options:
          title: Select options for inclusion in the Internal Developer Portal
          type: array
          items:
            type: string
            enum:
              - 'Add project to APIs'
              - 'Add project to CI/CD section'
              - 'Automatically create a Slack channel'
              - 'Add to projects section'
          uniqueItems: true
          ui:widget: checkboxes
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          group: ${{ parameters.group }}

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
